[tool.poetry]
name = "water-tracker"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "water_tracker"}]

[tool.poetry.dependencies]
python = "~3.10"
streamlit = "^1.20.0"
pandas = "<2.0.0"
requests = "^2.28.2"
numpy = "^1.24.2"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
ruff = "^0.0.260"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
