name: Test and Linting

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit install
      - name: Run pre-commit
        run: SKIP=no-commit-to-branch pre-commit run --all-files
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --only main
          pip install pytest pytest-cov
      - name: Run Pytest
        run: pytest --cov-report=html
        env:
          CDSAPI_URL: https://cds.climate.copernicus.eu/api/v2
          CDSAPI_KEY: 123456:1234a12a-1234-123a-a1a1-abcabcabcabc
